import { LanguageCode } from "@/contexts/LanguageContext";

export type CEFRLevel = 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';

export interface CEFRLevelInfo {
  code: CEFRLevel;
  name: Record<LanguageCode, string>;
  description: Record<LanguageCode, string>;
  color: string;
  icon: string;
  estimatedHours: number;
  order: number;
}

export interface CurriculumLesson {
  id: string;
  slug: string;
  cefrLevel: CEFRLevel;
  category: string;
  title: Record<LanguageCode, string>;
  description: Record<LanguageCode, string>;
  objectives: string[];
  estimatedMinutes: number;
  order: number;
  vocabulary: VocabularyItem[];
  grammarPoints: string[];
  culturalNotes?: string;
  exercises: ExerciseItem[];
}

export interface VocabularyItem {
  spanish: string;
  pronunciation: string;
  translations: Record<LanguageCode, string>;
  partOfSpeech: string;
  exampleSentence: string;
  exampleTranslation: string;
}

export interface ExerciseItem {
  id: string;
  type: 'multiple_choice' | 'fill_blank' | 'translation' | 'listening' | 'speaking' | 'matching';
  question: string;
  options?: string[];
  correctAnswer: string;
  explanation: string;
  points: number;
}

// CEFR Level Definitions
export const CEFR_LEVELS: CEFRLevelInfo[] = [
  {
    code: 'A1',
    name: {
      en: 'Breakthrough',
      es: 'Acceso',
      ar: 'المستوى التأسيسي',
      fr: 'Découverte',
      it: 'Livello base',
      de: 'Anfänger',
      zh: '入门级',
      ru: 'Начальный',
    },
    description: {
      en: 'Can understand and use familiar everyday expressions and very basic phrases. Can introduce themselves and ask simple questions.',
      es: 'Puede comprender y utilizar expresiones cotidianas de uso muy frecuente. Puede presentarse y hacer preguntas sencillas.',
      ar: 'يمكنه فهم واستخدام التعبيرات اليومية المألوفة والعبارات الأساسية جداً.',
      fr: 'Peut comprendre et utiliser des expressions familières et quotidiennes. Peut se présenter et poser des questions simples.',
      it: 'Può comprendere e usare espressioni familiari di uso quotidiano. Può presentarsi e fare domande semplici.',
      de: 'Kann vertraute, alltägliche Ausdrücke verstehen und verwenden. Kann sich vorstellen und einfache Fragen stellen.',
      zh: '能够理解和使用熟悉的日常表达和非常基本的短语。能够自我介绍并提出简单问题。',
      ru: 'Может понимать и использовать знакомые повседневные выражения. Может представиться и задавать простые вопросы.',
    },
    color: '#22c55e', // green-500
    icon: '🌱',
    estimatedHours: 80,
    order: 1,
  },
  {
    code: 'A2',
    name: {
      en: 'Waystage',
      es: 'Plataforma',
      ar: 'المستوى الابتدائي',
      fr: 'Survie',
      it: 'Livello elementare',
      de: 'Grundlagen',
      zh: '初级',
      ru: 'Элементарный',
    },
    description: {
      en: 'Can understand sentences related to areas of immediate relevance. Can communicate in simple, routine tasks requiring direct exchange of information.',
      es: 'Puede comprender frases relacionadas con áreas de relevancia inmediata. Puede comunicarse en tareas sencillas y rutinarias.',
      ar: 'يمكنه فهم الجمل المتعلقة بمجالات ذات صلة مباشرة. يمكنه التواصل في المهام البسيطة والروتينية.',
      fr: 'Peut comprendre des phrases liées à des domaines de pertinence immédiate. Peut communiquer lors de tâches simples et routinières.',
      it: 'Può comprendere frasi relative ad aree di immediata rilevanza. Può comunicare in compiti semplici e di routine.',
      de: 'Kann Sätze verstehen, die sich auf Bereiche von unmittelbarer Bedeutung beziehen. Kann in einfachen Routineaufgaben kommunizieren.',
      zh: '能够理解与直接相关领域有关的句子。能够在简单的日常任务中进行交流。',
      ru: 'Может понимать предложения, связанные с областями непосредственной значимости. Может общаться в простых рутинных задачах.',
    },
    color: '#84cc16', // lime-500
    icon: '🌿',
    estimatedHours: 100,
    order: 2,
  },
  {
    code: 'B1',
    name: {
      en: 'Threshold',
      es: 'Umbral',
      ar: 'المستوى المتوسط',
      fr: 'Seuil',
      it: 'Livello intermedio',
      de: 'Mittelstufe',
      zh: '中级',
      ru: 'Пороговый',
    },
    description: {
      en: 'Can understand the main points of clear standard input on familiar matters. Can deal with most situations likely to arise while travelling.',
      es: 'Puede comprender los puntos principales de textos claros sobre temas conocidos. Puede desenvolverse en la mayoría de situaciones de viaje.',
      ar: 'يمكنه فهم النقاط الرئيسية للمدخلات القياسية الواضحة حول الأمور المألوفة.',
      fr: 'Peut comprendre les points essentiels d\'un texte clair sur des sujets familiers. Peut se débrouiller dans la plupart des situations de voyage.',
      it: 'Può comprendere i punti principali di testi chiari su argomenti familiari. Può gestire la maggior parte delle situazioni di viaggio.',
      de: 'Kann die Hauptpunkte klarer Standardeingaben zu vertrauten Themen verstehen. Kann die meisten Reisesituationen bewältigen.',
      zh: '能够理解关于熟悉事务的清晰标准输入的要点。能够应对旅行中可能出现的大多数情况。',
      ru: 'Может понимать основные положения четкого стандартного текста по знакомым темам. Может справиться с большинством ситуаций в путешествии.',
    },
    color: '#eab308', // yellow-500
    icon: '🌳',
    estimatedHours: 150,
    order: 3,
  },
  {
    code: 'B2',
    name: {
      en: 'Vantage',
      es: 'Avanzado',
      ar: 'المستوى فوق المتوسط',
      fr: 'Avancé',
      it: 'Livello intermedio superiore',
      de: 'Selbständige Sprachverwendung',
      zh: '中高级',
      ru: 'Продвинутый',
    },
    description: {
      en: 'Can understand the main ideas of complex text on both concrete and abstract topics. Can interact with a degree of fluency and spontaneity.',
      es: 'Puede comprender las ideas principales de textos complejos sobre temas concretos y abstractos. Puede interactuar con fluidez y espontaneidad.',
      ar: 'يمكنه فهم الأفكار الرئيسية للنصوص المعقدة حول الموضوعات الملموسة والمجردة.',
      fr: 'Peut comprendre les idées principales de textes complexes sur des sujets concrets et abstraits. Peut interagir avec fluidité et spontanéité.',
      it: 'Può comprendere le idee principali di testi complessi su argomenti concreti e astratti. Può interagire con fluidità e spontaneità.',
      de: 'Kann die Hauptideen komplexer Texte zu konkreten und abstrakten Themen verstehen. Kann fließend und spontan interagieren.',
      zh: '能够理解关于具体和抽象主题的复杂文本的主要思想。能够流利自然地进行交流。',
      ru: 'Может понимать основные идеи сложных текстов на конкретные и абстрактные темы. Может взаимодействовать с определенной степенью беглости.',
    },
    color: '#f97316', // orange-500
    icon: '🌲',
    estimatedHours: 200,
    order: 4,
  },
  {
    code: 'C1',
    name: {
      en: 'Effective Operational Proficiency',
      es: 'Dominio Operativo Eficaz',
      ar: 'المستوى المتقدم',
      fr: 'Autonome',
      it: 'Livello avanzato',
      de: 'Fachkundige Sprachkenntnisse',
      zh: '高级',
      ru: 'Уровень профессионального владения',
    },
    description: {
      en: 'Can understand a wide range of demanding, longer texts, and recognize implicit meaning. Can express ideas fluently and spontaneously without much searching for expressions.',
      es: 'Puede comprender una amplia variedad de textos extensos y exigentes. Puede expresar ideas con fluidez y espontaneidad sin buscar expresiones.',
      ar: 'يمكنه فهم مجموعة واسعة من النصوص الطويلة والمتطلبة، والتعرف على المعنى الضمني.',
      fr: 'Peut comprendre une grande variété de textes longs et exigeants. Peut s\'exprimer avec fluidité et spontanéité sans trop chercher ses mots.',
      it: 'Può comprendere un\'ampia gamma di testi lunghi e impegnativi. Può esprimersi con fluidità e spontaneità senza cercare le parole.',
      de: 'Kann ein breites Spektrum anspruchsvoller, längerer Texte verstehen. Kann Ideen fließend und spontan ausdrücken.',
      zh: '能够理解各种要求较高的长篇文本，并识别隐含意义。能够流利自然地表达想法。',
      ru: 'Может понимать широкий спектр сложных длинных текстов. Может выражать идеи бегло и спонтанно.',
    },
    color: '#ef4444', // red-500
    icon: '🏔️',
    estimatedHours: 250,
    order: 5,
  },
  {
    code: 'C2',
    name: {
      en: 'Mastery',
      es: 'Maestría',
      ar: 'مستوى الإتقان',
      fr: 'Maîtrise',
      it: 'Livello di padronanza',
      de: 'Annähernd muttersprachliche Kenntnisse',
      zh: '精通级',
      ru: 'Уровень владения в совершенстве',
    },
    description: {
      en: 'Can understand with ease virtually everything heard or read. Can summarize information from different sources, reconstructing arguments coherently. Can express themselves spontaneously, very fluently and precisely.',
      es: 'Puede comprender con facilidad prácticamente todo lo que oye o lee. Puede resumir información de diferentes fuentes. Puede expresarse de forma espontánea, muy fluida y precisa.',
      ar: 'يمكنه فهم كل ما يسمعه أو يقرأه بسهولة تقريباً. يمكنه تلخيص المعلومات من مصادر مختلفة.',
      fr: 'Peut comprendre sans effort pratiquement tout ce qu\'il lit ou entend. Peut résumer des informations de différentes sources. Peut s\'exprimer spontanément, très couramment et avec précision.',
      it: 'Può comprendere senza sforzo praticamente tutto ciò che legge o ascolta. Può riassumere informazioni da diverse fonti. Può esprimersi spontaneamente, molto fluentemente e con precisione.',
      de: 'Kann praktisch alles, was er liest oder hört, mühelos verstehen. Kann Informationen aus verschiedenen Quellen zusammenfassen. Kann sich spontan, sehr fließend und genau ausdrücken.',
      zh: '能够轻松理解几乎所有听到或读到的内容。能够总结来自不同来源的信息。能够自然、非常流利和准确地表达自己。',
      ru: 'Может легко понимать практически всё услышанное или прочитанное. Может обобщать информацию из разных источников. Может выражаться спонтанно, очень бегло и точно.',
    },
    color: '#a855f7', // purple-500
    icon: '👑',
    estimatedHours: 300,
    order: 6,
  },
];

// Comprehensive Curriculum Lessons for All Levels
export const CURRICULUM_LESSONS: CurriculumLesson[] = [
  // ==================== A1 LESSONS ====================
  {
    id: 'a1-01',
    slug: 'greetings-and-introductions',
    cefrLevel: 'A1',
    category: 'basics',
    title: {
      en: 'Greetings and Introductions',
      es: 'Saludos y Presentaciones',
      ar: 'التحيات والتقديم',
      fr: 'Salutations et Présentations',
      it: 'Saluti e Presentazioni',
      de: 'Begrüßungen und Vorstellungen',
      zh: '问候和介绍',
      ru: 'Приветствия и Знакомства',
    },
    description: {
      en: 'Learn how to greet people and introduce yourself in Spanish',
      es: 'Aprende a saludar y presentarte en español',
      ar: 'تعلم كيفية تحية الناس وتقديم نفسك بالإسبانية',
      fr: 'Apprenez à saluer et à vous présenter en espagnol',
      it: 'Impara a salutare e presentarti in spagnolo',
      de: 'Lernen Sie, Menschen zu begrüßen und sich auf Spanisch vorzustellen',
      zh: '学习如何用西班牙语问候和自我介绍',
      ru: 'Научитесь приветствовать людей и представляться на испанском',
    },
    objectives: [
      'Greet people at different times of day',
      'Introduce yourself with name and origin',
      'Ask someone their name',
      'Use formal and informal greetings',
    ],
    estimatedMinutes: 20,
    order: 1,
    vocabulary: [
      {
        spanish: 'Hola',
        pronunciation: 'OH-lah',
        translations: { en: 'Hello', es: 'Hola', ar: 'مرحبا', fr: 'Bonjour', it: 'Ciao', de: 'Hallo', zh: '你好', ru: 'Привет' },
        partOfSpeech: 'interjection',
        exampleSentence: '¡Hola! ¿Cómo estás?',
        exampleTranslation: 'Hello! How are you?',
      },
      {
        spanish: 'Buenos días',
        pronunciation: 'BWEH-nohs DEE-ahs',
        translations: { en: 'Good morning', es: 'Buenos días', ar: 'صباح الخير', fr: 'Bonjour', it: 'Buongiorno', de: 'Guten Morgen', zh: '早上好', ru: 'Доброе утро' },
        partOfSpeech: 'phrase',
        exampleSentence: 'Buenos días, señor García.',
        exampleTranslation: 'Good morning, Mr. García.',
      },
      {
        spanish: 'Buenas tardes',
        pronunciation: 'BWEH-nahs TAR-dehs',
        translations: { en: 'Good afternoon', es: 'Buenas tardes', ar: 'مساء الخير', fr: 'Bon après-midi', it: 'Buon pomeriggio', de: 'Guten Tag', zh: '下午好', ru: 'Добрый день' },
        partOfSpeech: 'phrase',
        exampleSentence: 'Buenas tardes, ¿cómo está usted?',
        exampleTranslation: 'Good afternoon, how are you?',
      },
      {
        spanish: 'Buenas noches',
        pronunciation: 'BWEH-nahs NOH-chehs',
        translations: { en: 'Good evening/night', es: 'Buenas noches', ar: 'مساء الخير/تصبح على خير', fr: 'Bonsoir/Bonne nuit', it: 'Buonasera/Buonanotte', de: 'Guten Abend', zh: '晚上好', ru: 'Добрый вечер' },
        partOfSpeech: 'phrase',
        exampleSentence: 'Buenas noches, hasta mañana.',
        exampleTranslation: 'Good night, see you tomorrow.',
      },
      {
        spanish: 'Me llamo',
        pronunciation: 'meh YAH-moh',
        translations: { en: 'My name is', es: 'Me llamo', ar: 'اسمي', fr: 'Je m\'appelle', it: 'Mi chiamo', de: 'Ich heiße', zh: '我叫', ru: 'Меня зовут' },
        partOfSpeech: 'phrase',
        exampleSentence: 'Me llamo María.',
        exampleTranslation: 'My name is María.',
      },
      {
        spanish: 'Mucho gusto',
        pronunciation: 'MOO-choh GOOS-toh',
        translations: { en: 'Nice to meet you', es: 'Mucho gusto', ar: 'سعيد بلقائك', fr: 'Enchanté', it: 'Piacere', de: 'Freut mich', zh: '很高兴认识你', ru: 'Очень приятно' },
        partOfSpeech: 'phrase',
        exampleSentence: 'Mucho gusto, soy Carlos.',
        exampleTranslation: 'Nice to meet you, I\'m Carlos.',
      },
    ],
    grammarPoints: [
      'Ser vs Estar (introduction)',
      'Subject pronouns (yo, tú, usted)',
      'Formal vs informal address',
    ],
    culturalNotes: 'In Spanish-speaking countries, greetings often include physical contact like handshakes, hugs, or kisses on the cheek depending on the region and relationship.',
    exercises: [
      {
        id: 'a1-01-ex1',
        type: 'multiple_choice',
        question: 'How do you say "Good morning" in Spanish?',
        options: ['Buenas noches', 'Buenos días', 'Buenas tardes', 'Hola'],
        correctAnswer: 'Buenos días',
        explanation: '"Buenos días" is used in the morning until around noon.',
        points: 10,
      },
      {
        id: 'a1-01-ex2',
        type: 'fill_blank',
        question: 'Complete: "_____ María, mucho gusto."',
        correctAnswer: 'Me llamo',
        explanation: '"Me llamo" means "My name is" and is used to introduce yourself.',
        points: 10,
      },
      {
        id: 'a1-01-ex3',
        type: 'translation',
        question: 'Translate to Spanish: "Nice to meet you"',
        correctAnswer: 'Mucho gusto',
        explanation: '"Mucho gusto" literally means "much pleasure" and is the standard way to say "nice to meet you".',
        points: 15,
      },
    ],
  },
  {
    id: 'a1-02',
    slug: 'numbers-1-to-100',
    cefrLevel: 'A1',
    category: 'basics',
    title: {
      en: 'Numbers 1 to 100',
      es: 'Números del 1 al 100',
      ar: 'الأرقام من 1 إلى 100',
      fr: 'Les nombres de 1 à 100',
      it: 'Numeri da 1 a 100',
      de: 'Zahlen von 1 bis 100',
      zh: '数字1到100',
      ru: 'Числа от 1 до 100',
    },
    description: {
      en: 'Master Spanish numbers from one to one hundred',
      es: 'Domina los números en español del uno al cien',
      ar: 'أتقن الأرقام الإسبانية من واحد إلى مائة',
      fr: 'Maîtrisez les nombres espagnols de un à cent',
      it: 'Padroneggia i numeri spagnoli da uno a cento',
      de: 'Beherrschen Sie die spanischen Zahlen von eins bis hundert',
      zh: '掌握西班牙语数字从一到一百',
      ru: 'Освойте испанские числа от одного до ста',
    },
    objectives: [
      'Count from 1 to 20',
      'Learn tens (30, 40, 50...)',
      'Form compound numbers',
      'Use numbers in context',
    ],
    estimatedMinutes: 25,
    order: 2,
    vocabulary: [
      {
        spanish: 'uno',
        pronunciation: 'OO-noh',
        translations: { en: 'one', es: 'uno', ar: 'واحد', fr: 'un', it: 'uno', de: 'eins', zh: '一', ru: 'один' },
        partOfSpeech: 'number',
        exampleSentence: 'Tengo un hermano.',
        exampleTranslation: 'I have one brother.',
      },
      {
        spanish: 'diez',
        pronunciation: 'dee-EHS',
        translations: { en: 'ten', es: 'diez', ar: 'عشرة', fr: 'dix', it: 'dieci', de: 'zehn', zh: '十', ru: 'десять' },
        partOfSpeech: 'number',
        exampleSentence: 'Son las diez de la mañana.',
        exampleTranslation: 'It\'s ten in the morning.',
      },
      {
        spanish: 'veinte',
        pronunciation: 'BAYN-teh',
        translations: { en: 'twenty', es: 'veinte', ar: 'عشرون', fr: 'vingt', it: 'venti', de: 'zwanzig', zh: '二十', ru: 'двадцать' },
        partOfSpeech: 'number',
        exampleSentence: 'Tengo veinte años.',
        exampleTranslation: 'I am twenty years old.',
      },
      {
        spanish: 'cincuenta',
        pronunciation: 'seen-KWEN-tah',
        translations: { en: 'fifty', es: 'cincuenta', ar: 'خمسون', fr: 'cinquante', it: 'cinquanta', de: 'fünfzig', zh: '五十', ru: 'пятьдесят' },
        partOfSpeech: 'number',
        exampleSentence: 'El libro cuesta cincuenta euros.',
        exampleTranslation: 'The book costs fifty euros.',
      },
      {
        spanish: 'cien',
        pronunciation: 'see-EHN',
        translations: { en: 'one hundred', es: 'cien', ar: 'مائة', fr: 'cent', it: 'cento', de: 'hundert', zh: '一百', ru: 'сто' },
        partOfSpeech: 'number',
        exampleSentence: 'Hay cien personas en la sala.',
        exampleTranslation: 'There are one hundred people in the room.',
      },
    ],
    grammarPoints: [
      'Number agreement (uno/una)',
      'Numbers 16-19 (special forms)',
      'Compound numbers with "y"',
    ],
    exercises: [
      {
        id: 'a1-02-ex1',
        type: 'multiple_choice',
        question: 'What is "42" in Spanish?',
        options: ['cuarenta y dos', 'cuatro y dos', 'cuarenta dos', 'cuatro dos'],
        correctAnswer: 'cuarenta y dos',
        explanation: 'Compound numbers from 31-99 use "y" (and) between the tens and units.',
        points: 10,
      },
      {
        id: 'a1-02-ex2',
        type: 'fill_blank',
        question: 'Tengo _____ años. (25)',
        correctAnswer: 'veinticinco',
        explanation: 'Numbers 21-29 are written as one word: veintiuno, veintidós, veintitrés, etc.',
        points: 10,
      },
    ],
  },
  {
    id: 'a1-03',
    slug: 'colors-and-basic-adjectives',
    cefrLevel: 'A1',
    category: 'vocabulary',
    title: {
      en: 'Colors and Basic Adjectives',
      es: 'Colores y Adjetivos Básicos',
      ar: 'الألوان والصفات الأساسية',
      fr: 'Couleurs et Adjectifs de Base',
      it: 'Colori e Aggettivi di Base',
      de: 'Farben und Grundlegende Adjektive',
      zh: '颜色和基本形容词',
      ru: 'Цвета и Базовые Прилагательные',
    },
    description: {
      en: 'Learn colors and basic descriptive adjectives in Spanish',
      es: 'Aprende los colores y adjetivos descriptivos básicos en español',
      ar: 'تعلم الألوان والصفات الوصفية الأساسية بالإسبانية',
      fr: 'Apprenez les couleurs et les adjectifs descriptifs de base en espagnol',
      it: 'Impara i colori e gli aggettivi descrittivi di base in spagnolo',
      de: 'Lernen Sie Farben und grundlegende beschreibende Adjektive auf Spanisch',
      zh: '学习西班牙语中的颜色和基本描述性形容词',
      ru: 'Изучите цвета и базовые описательные прилагательные на испанском',
    },
    objectives: [
      'Name all basic colors',
      'Use adjectives to describe objects',
      'Understand adjective agreement',
      'Position adjectives correctly',
    ],
    estimatedMinutes: 20,
    order: 3,
    vocabulary: [
      {
        spanish: 'rojo',
        pronunciation: 'ROH-hoh',
        translations: { en: 'red', es: 'rojo', ar: 'أحمر', fr: 'rouge', it: 'rosso', de: 'rot', zh: '红色', ru: 'красный' },
        partOfSpeech: 'adjective',
        exampleSentence: 'La manzana es roja.',
        exampleTranslation: 'The apple is red.',
      },
      {
        spanish: 'grande',
        pronunciation: 'GRAHN-deh',
        translations: { en: 'big/large', es: 'grande', ar: 'كبير', fr: 'grand', it: 'grande', de: 'groß', zh: '大的', ru: 'большой' },
        partOfSpeech: 'adjective',
        exampleSentence: 'Es una casa grande.',
        exampleTranslation: 'It\'s a big house.',
      },
      {
        spanish: 'pequeño',
        pronunciation: 'peh-KEH-nyoh',
        translations: { en: 'small', es: 'pequeño', ar: 'صغير', fr: 'petit', it: 'piccolo', de: 'klein', zh: '小的', ru: 'маленький' },
        partOfSpeech: 'adjective',
        exampleSentence: 'El gato es pequeño.',
        exampleTranslation: 'The cat is small.',
      },
      {
        spanish: 'azul',
        pronunciation: 'ah-SOOL',
        translations: { en: 'blue', es: 'azul', ar: 'أزرق', fr: 'bleu', it: 'blu', de: 'blau', zh: '蓝色', ru: 'синий' },
        partOfSpeech: 'adjective',
        exampleSentence: 'El cielo es azul.',
        exampleTranslation: 'The sky is blue.',
      },
    ],
    grammarPoints: [
      'Adjective gender agreement (-o/-a)',
      'Adjective number agreement (-s/-es)',
      'Adjective placement (after noun)',
    ],
    exercises: [
      {
        id: 'a1-03-ex1',
        type: 'multiple_choice',
        question: 'How do you say "The white house" in Spanish?',
        options: ['La casa blanca', 'El casa blanco', 'La blanca casa', 'El blanco casa'],
        correctAnswer: 'La casa blanca',
        explanation: 'Casa is feminine, so we use "la" and "blanca" (feminine form of blanco).',
        points: 10,
      },
    ],
  },
  {
    id: 'a1-04',
    slug: 'family-members',
    cefrLevel: 'A1',
    category: 'vocabulary',
    title: {
      en: 'Family Members',
      es: 'Miembros de la Familia',
      ar: 'أفراد العائلة',
      fr: 'Membres de la Famille',
      it: 'Membri della Famiglia',
      de: 'Familienmitglieder',
      zh: '家庭成员',
      ru: 'Члены Семьи',
    },
    description: {
      en: 'Learn vocabulary for family relationships in Spanish',
      es: 'Aprende vocabulario sobre relaciones familiares en español',
      ar: 'تعلم مفردات العلاقات العائلية بالإسبانية',
      fr: 'Apprenez le vocabulaire des relations familiales en espagnol',
      it: 'Impara il vocabolario delle relazioni familiari in spagnolo',
      de: 'Lernen Sie Vokabeln für Familienbeziehungen auf Spanisch',
      zh: '学习西班牙语中的家庭关系词汇',
      ru: 'Изучите словарь семейных отношений на испанском',
    },
    objectives: [
      'Name immediate family members',
      'Describe your family',
      'Use possessive adjectives',
      'Talk about family relationships',
    ],
    estimatedMinutes: 20,
    order: 4,
    vocabulary: [
      {
        spanish: 'madre',
        pronunciation: 'MAH-dreh',
        translations: { en: 'mother', es: 'madre', ar: 'أم', fr: 'mère', it: 'madre', de: 'Mutter', zh: '母亲', ru: 'мать' },
        partOfSpeech: 'noun',
        exampleSentence: 'Mi madre se llama Ana.',
        exampleTranslation: 'My mother\'s name is Ana.',
      },
      {
        spanish: 'padre',
        pronunciation: 'PAH-dreh',
        translations: { en: 'father', es: 'padre', ar: 'أب', fr: 'père', it: 'padre', de: 'Vater', zh: '父亲', ru: 'отец' },
        partOfSpeech: 'noun',
        exampleSentence: 'Mi padre trabaja en una oficina.',
        exampleTranslation: 'My father works in an office.',
      },
      {
        spanish: 'hermano/hermana',
        pronunciation: 'ehr-MAH-noh/ehr-MAH-nah',
        translations: { en: 'brother/sister', es: 'hermano/hermana', ar: 'أخ/أخت', fr: 'frère/sœur', it: 'fratello/sorella', de: 'Bruder/Schwester', zh: '兄弟/姐妹', ru: 'брат/сестра' },
        partOfSpeech: 'noun',
        exampleSentence: 'Tengo dos hermanos y una hermana.',
        exampleTranslation: 'I have two brothers and one sister.',
      },
      {
        spanish: 'abuelo/abuela',
        pronunciation: 'ah-BWEH-loh/ah-BWEH-lah',
        translations: { en: 'grandfather/grandmother', es: 'abuelo/abuela', ar: 'جد/جدة', fr: 'grand-père/grand-mère', it: 'nonno/nonna', de: 'Großvater/Großmutter', zh: '祖父/祖母', ru: 'дедушка/бабушка' },
        partOfSpeech: 'noun',
        exampleSentence: 'Mis abuelos viven en México.',
        exampleTranslation: 'My grandparents live in Mexico.',
      },
    ],
    grammarPoints: [
      'Possessive adjectives (mi, tu, su)',
      'Plural forms of family nouns',
      'Using "tener" for family members',
    ],
    exercises: [
      {
        id: 'a1-04-ex1',
        type: 'matching',
        question: 'Match the Spanish family terms with their English equivalents',
        correctAnswer: 'madre-mother, padre-father, hermano-brother, hermana-sister',
        explanation: 'These are the basic family terms you should memorize.',
        points: 15,
      },
    ],
  },
  {
    id: 'a1-05',
    slug: 'ser-and-estar-basics',
    cefrLevel: 'A1',
    category: 'grammar',
    title: {
      en: 'Ser and Estar: The Basics',
      es: 'Ser y Estar: Lo Básico',
      ar: 'Ser و Estar: الأساسيات',
      fr: 'Ser et Estar : Les Bases',
      it: 'Ser ed Estar: Le Basi',
      de: 'Ser und Estar: Die Grundlagen',
      zh: 'Ser和Estar：基础',
      ru: 'Ser и Estar: Основы',
    },
    description: {
      en: 'Understand the fundamental difference between ser and estar',
      es: 'Comprende la diferencia fundamental entre ser y estar',
      ar: 'افهم الفرق الأساسي بين ser و estar',
      fr: 'Comprenez la différence fondamentale entre ser et estar',
      it: 'Comprendi la differenza fondamentale tra ser ed estar',
      de: 'Verstehen Sie den grundlegenden Unterschied zwischen ser und estar',
      zh: '理解ser和estar之间的基本区别',
      ru: 'Поймите фундаментальную разницу между ser и estar',
    },
    objectives: [
      'Conjugate ser in present tense',
      'Conjugate estar in present tense',
      'Know when to use ser',
      'Know when to use estar',
    ],
    estimatedMinutes: 30,
    order: 5,
    vocabulary: [
      {
        spanish: 'ser',
        pronunciation: 'sehr',
        translations: { en: 'to be (permanent)', es: 'ser', ar: 'يكون (دائم)', fr: 'être (permanent)', it: 'essere (permanente)', de: 'sein (dauerhaft)', zh: '是（永久）', ru: 'быть (постоянно)' },
        partOfSpeech: 'verb',
        exampleSentence: 'Soy estudiante.',
        exampleTranslation: 'I am a student.',
      },
      {
        spanish: 'estar',
        pronunciation: 'ehs-TAHR',
        translations: { en: 'to be (temporary)', es: 'estar', ar: 'يكون (مؤقت)', fr: 'être (temporaire)', it: 'essere (temporaneo)', de: 'sein (vorübergehend)', zh: '是（暂时）', ru: 'быть (временно)' },
        partOfSpeech: 'verb',
        exampleSentence: 'Estoy cansado.',
        exampleTranslation: 'I am tired.',
      },
    ],
    grammarPoints: [
      'Ser: identity, origin, profession, characteristics',
      'Estar: location, emotions, temporary states',
      'Present tense conjugations',
      'Common expressions with each verb',
    ],
    culturalNotes: 'The ser/estar distinction is one of the most challenging aspects for English speakers learning Spanish, as English uses only "to be" for both concepts.',
    exercises: [
      {
        id: 'a1-05-ex1',
        type: 'multiple_choice',
        question: 'Which verb completes: "María ___ de España."',
        options: ['es', 'está', 'son', 'están'],
        correctAnswer: 'es',
        explanation: 'We use "ser" for origin. María is from Spain (permanent characteristic).',
        points: 10,
      },
      {
        id: 'a1-05-ex2',
        type: 'multiple_choice',
        question: 'Which verb completes: "El libro ___ en la mesa."',
        options: ['es', 'está', 'ser', 'estar'],
        correctAnswer: 'está',
        explanation: 'We use "estar" for location. The book is on the table.',
        points: 10,
      },
    ],
  },

  // ==================== A2 LESSONS ====================
  {
    id: 'a2-01',
    slug: 'daily-routines',
    cefrLevel: 'A2',
    category: 'vocabulary',
    title: {
      en: 'Daily Routines',
      es: 'Rutinas Diarias',
      ar: 'الروتين اليومي',
      fr: 'Routines Quotidiennes',
      it: 'Routine Quotidiane',
      de: 'Tägliche Routinen',
      zh: '日常生活',
      ru: 'Ежедневные Рутины',
    },
    description: {
      en: 'Describe your daily activities and habits in Spanish',
      es: 'Describe tus actividades diarias y hábitos en español',
      ar: 'صف أنشطتك اليومية وعاداتك بالإسبانية',
      fr: 'Décrivez vos activités quotidiennes et habitudes en espagnol',
      it: 'Descrivi le tue attività quotidiane e abitudini in spagnolo',
      de: 'Beschreiben Sie Ihre täglichen Aktivitäten und Gewohnheiten auf Spanisch',
      zh: '用西班牙语描述你的日常活动和习惯',
      ru: 'Опишите свои ежедневные занятия и привычки на испанском',
    },
    objectives: [
      'Describe morning routines',
      'Talk about work/school activities',
      'Describe evening activities',
      'Use reflexive verbs correctly',
    ],
    estimatedMinutes: 25,
    order: 1,
    vocabulary: [
      {
        spanish: 'despertarse',
        pronunciation: 'dehs-pehr-TAHR-seh',
        translations: { en: 'to wake up', es: 'despertarse', ar: 'يستيقظ', fr: 'se réveiller', it: 'svegliarsi', de: 'aufwachen', zh: '醒来', ru: 'просыпаться' },
        partOfSpeech: 'reflexive verb',
        exampleSentence: 'Me despierto a las siete.',
        exampleTranslation: 'I wake up at seven.',
      },
      {
        spanish: 'ducharse',
        pronunciation: 'doo-CHAHR-seh',
        translations: { en: 'to shower', es: 'ducharse', ar: 'يستحم', fr: 'se doucher', it: 'farsi la doccia', de: 'duschen', zh: '淋浴', ru: 'принимать душ' },
        partOfSpeech: 'reflexive verb',
        exampleSentence: 'Me ducho por la mañana.',
        exampleTranslation: 'I shower in the morning.',
      },
      {
        spanish: 'desayunar',
        pronunciation: 'deh-sah-yoo-NAHR',
        translations: { en: 'to have breakfast', es: 'desayunar', ar: 'يتناول الفطور', fr: 'prendre le petit-déjeuner', it: 'fare colazione', de: 'frühstücken', zh: '吃早餐', ru: 'завтракать' },
        partOfSpeech: 'verb',
        exampleSentence: 'Desayuno café y tostadas.',
        exampleTranslation: 'I have coffee and toast for breakfast.',
      },
      {
        spanish: 'acostarse',
        pronunciation: 'ah-kohs-TAHR-seh',
        translations: { en: 'to go to bed', es: 'acostarse', ar: 'يذهب للنوم', fr: 'se coucher', it: 'andare a letto', de: 'ins Bett gehen', zh: '睡觉', ru: 'ложиться спать' },
        partOfSpeech: 'reflexive verb',
        exampleSentence: 'Me acuesto a las once.',
        exampleTranslation: 'I go to bed at eleven.',
      },
    ],
    grammarPoints: [
      'Reflexive verbs and pronouns',
      'Time expressions (por la mañana, por la tarde)',
      'Frequency adverbs (siempre, nunca, a veces)',
    ],
    exercises: [
      {
        id: 'a2-01-ex1',
        type: 'fill_blank',
        question: 'Yo _____ (levantarse) a las seis de la mañana.',
        correctAnswer: 'me levanto',
        explanation: 'Reflexive verbs require the reflexive pronoun (me) before the conjugated verb.',
        points: 10,
      },
    ],
  },
  {
    id: 'a2-02',
    slug: 'past-tense-preterite',
    cefrLevel: 'A2',
    category: 'grammar',
    title: {
      en: 'Past Tense: Pretérito Indefinido',
      es: 'Tiempo Pasado: Pretérito Indefinido',
      ar: 'الماضي: Pretérito Indefinido',
      fr: 'Passé : Pretérito Indefinido',
      it: 'Passato: Pretérito Indefinido',
      de: 'Vergangenheit: Pretérito Indefinido',
      zh: '过去时：简单过去时',
      ru: 'Прошедшее время: Pretérito Indefinido',
    },
    description: {
      en: 'Learn to talk about completed past actions',
      es: 'Aprende a hablar sobre acciones pasadas completadas',
      ar: 'تعلم التحدث عن الأفعال الماضية المكتملة',
      fr: 'Apprenez à parler d\'actions passées terminées',
      it: 'Impara a parlare di azioni passate completate',
      de: 'Lernen Sie, über abgeschlossene vergangene Handlungen zu sprechen',
      zh: '学习谈论已完成的过去行为',
      ru: 'Научитесь говорить о завершенных прошлых действиях',
    },
    objectives: [
      'Conjugate regular -ar verbs in preterite',
      'Conjugate regular -er/-ir verbs in preterite',
      'Learn common irregular preterites',
      'Use time markers for past events',
    ],
    estimatedMinutes: 35,
    order: 2,
    vocabulary: [
      {
        spanish: 'ayer',
        pronunciation: 'ah-YEHR',
        translations: { en: 'yesterday', es: 'ayer', ar: 'أمس', fr: 'hier', it: 'ieri', de: 'gestern', zh: '昨天', ru: 'вчера' },
        partOfSpeech: 'adverb',
        exampleSentence: 'Ayer fui al cine.',
        exampleTranslation: 'Yesterday I went to the cinema.',
      },
      {
        spanish: 'la semana pasada',
        pronunciation: 'lah seh-MAH-nah pah-SAH-dah',
        translations: { en: 'last week', es: 'la semana pasada', ar: 'الأسبوع الماضي', fr: 'la semaine dernière', it: 'la settimana scorsa', de: 'letzte Woche', zh: '上周', ru: 'на прошлой неделе' },
        partOfSpeech: 'phrase',
        exampleSentence: 'La semana pasada visité a mis abuelos.',
        exampleTranslation: 'Last week I visited my grandparents.',
      },
    ],
    grammarPoints: [
      'Regular -ar preterite endings (-é, -aste, -ó, -amos, -asteis, -aron)',
      'Regular -er/-ir preterite endings (-í, -iste, -ió, -imos, -isteis, -ieron)',
      'Irregular verbs: ir/ser, hacer, tener, estar',
      'Spelling changes in preterite',
    ],
    exercises: [
      {
        id: 'a2-02-ex1',
        type: 'multiple_choice',
        question: 'How do you say "I spoke" (hablar) in Spanish?',
        options: ['hablo', 'hablé', 'hablaba', 'hablaré'],
        correctAnswer: 'hablé',
        explanation: 'The preterite of "hablar" for "yo" is "hablé" (-é ending for -ar verbs).',
        points: 10,
      },
    ],
  },
  {
    id: 'a2-03',
    slug: 'shopping-and-prices',
    cefrLevel: 'A2',
    category: 'practical',
    title: {
      en: 'Shopping and Prices',
      es: 'Compras y Precios',
      ar: 'التسوق والأسعار',
      fr: 'Shopping et Prix',
      it: 'Shopping e Prezzi',
      de: 'Einkaufen und Preise',
      zh: '购物和价格',
      ru: 'Покупки и Цены',
    },
    description: {
      en: 'Learn to shop and discuss prices in Spanish',
      es: 'Aprende a comprar y hablar de precios en español',
      ar: 'تعلم التسوق ومناقشة الأسعار بالإسبانية',
      fr: 'Apprenez à faire du shopping et discuter des prix en espagnol',
      it: 'Impara a fare shopping e discutere i prezzi in spagnolo',
      de: 'Lernen Sie, auf Spanisch einzukaufen und über Preise zu sprechen',
      zh: '学习用西班牙语购物和讨论价格',
      ru: 'Научитесь делать покупки и обсуждать цены на испанском',
    },
    objectives: [
      'Ask for prices',
      'Describe clothing and sizes',
      'Use demonstrative adjectives',
      'Make purchases',
    ],
    estimatedMinutes: 25,
    order: 3,
    vocabulary: [
      {
        spanish: '¿Cuánto cuesta?',
        pronunciation: 'KWAHN-toh KWEHS-tah',
        translations: { en: 'How much does it cost?', es: '¿Cuánto cuesta?', ar: 'كم يكلف؟', fr: 'Combien ça coûte ?', it: 'Quanto costa?', de: 'Wie viel kostet es?', zh: '多少钱？', ru: 'Сколько это стоит?' },
        partOfSpeech: 'phrase',
        exampleSentence: '¿Cuánto cuesta esta camisa?',
        exampleTranslation: 'How much does this shirt cost?',
      },
      {
        spanish: 'barato/caro',
        pronunciation: 'bah-RAH-toh/KAH-roh',
        translations: { en: 'cheap/expensive', es: 'barato/caro', ar: 'رخيص/غالي', fr: 'bon marché/cher', it: 'economico/caro', de: 'billig/teuer', zh: '便宜/贵', ru: 'дешевый/дорогой' },
        partOfSpeech: 'adjective',
        exampleSentence: 'Este vestido es muy caro.',
        exampleTranslation: 'This dress is very expensive.',
      },
    ],
    grammarPoints: [
      'Demonstrative adjectives (este, ese, aquel)',
      'Direct object pronouns',
      'Comparatives (más...que, menos...que)',
    ],
    exercises: [
      {
        id: 'a2-03-ex1',
        type: 'translation',
        question: 'Translate: "I want to buy this blue shirt."',
        correctAnswer: 'Quiero comprar esta camisa azul.',
        explanation: 'Use "esta" (feminine) to match "camisa" (feminine noun).',
        points: 15,
      },
    ],
  },

  // ==================== B1 LESSONS ====================
  {
    id: 'b1-01',
    slug: 'expressing-opinions',
    cefrLevel: 'B1',
    category: 'communication',
    title: {
      en: 'Expressing Opinions',
      es: 'Expresar Opiniones',
      ar: 'التعبير عن الآراء',
      fr: 'Exprimer des Opinions',
      it: 'Esprimere Opinioni',
      de: 'Meinungen Ausdrücken',
      zh: '表达意见',
      ru: 'Выражение Мнений',
    },
    description: {
      en: 'Learn to express and defend your opinions in Spanish',
      es: 'Aprende a expresar y defender tus opiniones en español',
      ar: 'تعلم التعبير عن آرائك والدفاع عنها بالإسبانية',
      fr: 'Apprenez à exprimer et défendre vos opinions en espagnol',
      it: 'Impara a esprimere e difendere le tue opinioni in spagnolo',
      de: 'Lernen Sie, Ihre Meinungen auf Spanisch auszudrücken und zu verteidigen',
      zh: '学习用西班牙语表达和捍卫你的观点',
      ru: 'Научитесь выражать и защищать свое мнение на испанском',
    },
    objectives: [
      'Use opinion phrases',
      'Agree and disagree politely',
      'Give reasons for opinions',
      'Use subjunctive with opinion verbs',
    ],
    estimatedMinutes: 30,
    order: 1,
    vocabulary: [
      {
        spanish: 'Creo que',
        pronunciation: 'KREH-oh keh',
        translations: { en: 'I think that', es: 'Creo que', ar: 'أعتقد أن', fr: 'Je pense que', it: 'Penso che', de: 'Ich denke, dass', zh: '我认为', ru: 'Я думаю, что' },
        partOfSpeech: 'phrase',
        exampleSentence: 'Creo que es una buena idea.',
        exampleTranslation: 'I think it\'s a good idea.',
      },
      {
        spanish: 'En mi opinión',
        pronunciation: 'ehn mee oh-pee-nee-OHN',
        translations: { en: 'In my opinion', es: 'En mi opinión', ar: 'في رأيي', fr: 'À mon avis', it: 'Secondo me', de: 'Meiner Meinung nach', zh: '在我看来', ru: 'По моему мнению' },
        partOfSpeech: 'phrase',
        exampleSentence: 'En mi opinión, deberíamos esperar.',
        exampleTranslation: 'In my opinion, we should wait.',
      },
      {
        spanish: 'Estoy de acuerdo',
        pronunciation: 'ehs-TOY deh ah-KWEHR-doh',
        translations: { en: 'I agree', es: 'Estoy de acuerdo', ar: 'أوافق', fr: 'Je suis d\'accord', it: 'Sono d\'accordo', de: 'Ich stimme zu', zh: '我同意', ru: 'Я согласен' },
        partOfSpeech: 'phrase',
        exampleSentence: 'Estoy de acuerdo contigo.',
        exampleTranslation: 'I agree with you.',
      },
      {
        spanish: 'No estoy de acuerdo',
        pronunciation: 'noh ehs-TOY deh ah-KWEHR-doh',
        translations: { en: 'I disagree', es: 'No estoy de acuerdo', ar: 'لا أوافق', fr: 'Je ne suis pas d\'accord', it: 'Non sono d\'accordo', de: 'Ich stimme nicht zu', zh: '我不同意', ru: 'Я не согласен' },
        partOfSpeech: 'phrase',
        exampleSentence: 'No estoy de acuerdo con esa decisión.',
        exampleTranslation: 'I disagree with that decision.',
      },
    ],
    grammarPoints: [
      'Indicative vs subjunctive with opinion verbs',
      'Connectors for argumentation (porque, ya que, por eso)',
      'Conditional for polite disagreement',
    ],
    exercises: [
      {
        id: 'b1-01-ex1',
        type: 'multiple_choice',
        question: 'Complete: "No creo que ___ (ser) una buena idea."',
        options: ['es', 'sea', 'será', 'fue'],
        correctAnswer: 'sea',
        explanation: 'After "no creo que" (negative belief), we use subjunctive: "sea".',
        points: 15,
      },
    ],
  },
  {
    id: 'b1-02',
    slug: 'subjunctive-introduction',
    cefrLevel: 'B1',
    category: 'grammar',
    title: {
      en: 'Introduction to the Subjunctive',
      es: 'Introducción al Subjuntivo',
      ar: 'مقدمة إلى صيغة الشرط',
      fr: 'Introduction au Subjonctif',
      it: 'Introduzione al Congiuntivo',
      de: 'Einführung in den Subjunktiv',
      zh: '虚拟语气入门',
      ru: 'Введение в Сослагательное Наклонение',
    },
    description: {
      en: 'Understand when and how to use the Spanish subjunctive mood',
      es: 'Comprende cuándo y cómo usar el modo subjuntivo en español',
      ar: 'افهم متى وكيف تستخدم صيغة الشرط الإسبانية',
      fr: 'Comprenez quand et comment utiliser le subjonctif espagnol',
      it: 'Comprendi quando e come usare il congiuntivo spagnolo',
      de: 'Verstehen Sie, wann und wie Sie den spanischen Subjunktiv verwenden',
      zh: '了解何时以及如何使用西班牙语虚拟语气',
      ru: 'Поймите, когда и как использовать испанское сослагательное наклонение',
    },
    objectives: [
      'Conjugate regular verbs in present subjunctive',
      'Identify subjunctive triggers',
      'Use subjunctive with wishes and desires',
      'Use subjunctive with doubt and denial',
    ],
    estimatedMinutes: 40,
    order: 2,
    vocabulary: [
      {
        spanish: 'Quiero que',
        pronunciation: 'kee-EH-roh keh',
        translations: { en: 'I want (someone) to', es: 'Quiero que', ar: 'أريد أن', fr: 'Je veux que', it: 'Voglio che', de: 'Ich will, dass', zh: '我想要（某人）', ru: 'Я хочу, чтобы' },
        partOfSpeech: 'phrase',
        exampleSentence: 'Quiero que vengas a la fiesta.',
        exampleTranslation: 'I want you to come to the party.',
      },
      {
        spanish: 'Es importante que',
        pronunciation: 'ehs eem-pohr-TAHN-teh keh',
        translations: { en: 'It\'s important that', es: 'Es importante que', ar: 'من المهم أن', fr: 'Il est important que', it: 'È importante che', de: 'Es ist wichtig, dass', zh: '重要的是', ru: 'Важно, чтобы' },
        partOfSpeech: 'phrase',
        exampleSentence: 'Es importante que estudies.',
        exampleTranslation: 'It\'s important that you study.',
      },
    ],
    grammarPoints: [
      'Present subjunctive formation',
      'WEIRDO categories (Wishes, Emotions, Impersonal, Recommendations, Doubt, Ojalá)',
      'Subjunctive vs indicative contrast',
      'Common irregular subjunctive forms',
    ],
    exercises: [
      {
        id: 'b1-02-ex1',
        type: 'fill_blank',
        question: 'Espero que tú _____ (poder) venir mañana.',
        correctAnswer: 'puedas',
        explanation: '"Esperar que" triggers subjunctive. "Poder" becomes "puedas" in present subjunctive.',
        points: 15,
      },
    ],
  },

  // ==================== B2 LESSONS ====================
  {
    id: 'b2-01',
    slug: 'subjunctive-all-tenses',
    cefrLevel: 'B2',
    category: 'grammar',
    title: {
      en: 'Subjunctive: All Tenses',
      es: 'Subjuntivo: Todos los Tiempos',
      ar: 'صيغة الشرط: جميع الأزمنة',
      fr: 'Subjonctif : Tous les Temps',
      it: 'Congiuntivo: Tutti i Tempi',
      de: 'Subjunktiv: Alle Zeiten',
      zh: '虚拟语气：所有时态',
      ru: 'Сослагательное Наклонение: Все Времена',
    },
    description: {
      en: 'Master the subjunctive in past, present, and future contexts',
      es: 'Domina el subjuntivo en contextos pasados, presentes y futuros',
      ar: 'أتقن صيغة الشرط في السياقات الماضية والحاضرة والمستقبلية',
      fr: 'Maîtrisez le subjonctif dans les contextes passés, présents et futurs',
      it: 'Padroneggia il congiuntivo nei contesti passati, presenti e futuri',
      de: 'Beherrschen Sie den Subjunktiv in vergangenen, gegenwärtigen und zukünftigen Kontexten',
      zh: '掌握过去、现在和将来语境中的虚拟语气',
      ru: 'Освойте сослагательное наклонение в прошлом, настоящем и будущем контекстах',
    },
    objectives: [
      'Use imperfect subjunctive',
      'Form pluperfect subjunctive',
      'Understand sequence of tenses',
      'Use conditional sentences (si clauses)',
    ],
    estimatedMinutes: 45,
    order: 1,
    vocabulary: [
      {
        spanish: 'Si yo fuera',
        pronunciation: 'see yoh FWEH-rah',
        translations: { en: 'If I were', es: 'Si yo fuera', ar: 'لو كنت', fr: 'Si j\'étais', it: 'Se fossi', de: 'Wenn ich wäre', zh: '如果我是', ru: 'Если бы я был' },
        partOfSpeech: 'phrase',
        exampleSentence: 'Si yo fuera rico, viajaría por el mundo.',
        exampleTranslation: 'If I were rich, I would travel the world.',
      },
      {
        spanish: 'hubiera/hubiese',
        pronunciation: 'oo-bee-EH-rah/oo-bee-EH-seh',
        translations: { en: 'had (subjunctive)', es: 'hubiera/hubiese', ar: 'كان قد (شرطي)', fr: 'eusse/eût', it: 'avessi', de: 'hätte (Konjunktiv)', zh: '曾经（虚拟）', ru: 'имел бы' },
        partOfSpeech: 'verb',
        exampleSentence: 'Si hubiera sabido, habría venido.',
        exampleTranslation: 'If I had known, I would have come.',
      },
    ],
    grammarPoints: [
      'Imperfect subjunctive (-ra and -se forms)',
      'Pluperfect subjunctive formation',
      'Conditional sentences types 2 and 3',
      'Sequence of tenses in subjunctive',
    ],
    exercises: [
      {
        id: 'b2-01-ex1',
        type: 'fill_blank',
        question: 'Si _____ (tener) más tiempo, estudiaría más.',
        correctAnswer: 'tuviera',
        explanation: 'Type 2 conditional uses imperfect subjunctive in the si-clause.',
        points: 15,
      },
    ],
  },
  {
    id: 'b2-02',
    slug: 'debating-complex-topics',
    cefrLevel: 'B2',
    category: 'communication',
    title: {
      en: 'Debating Complex Topics',
      es: 'Debatir Temas Complejos',
      ar: 'مناقشة المواضيع المعقدة',
      fr: 'Débattre de Sujets Complexes',
      it: 'Dibattere Argomenti Complessi',
      de: 'Komplexe Themen Debattieren',
      zh: '辩论复杂话题',
      ru: 'Обсуждение Сложных Тем',
    },
    description: {
      en: 'Develop skills to discuss and debate complex social and political topics',
      es: 'Desarrolla habilidades para discutir y debatir temas sociales y políticos complejos',
      ar: 'طور مهارات مناقشة ومناظرة المواضيع الاجتماعية والسياسية المعقدة',
      fr: 'Développez des compétences pour discuter et débattre de sujets sociaux et politiques complexes',
      it: 'Sviluppa competenze per discutere e dibattere argomenti sociali e politici complessi',
      de: 'Entwickeln Sie Fähigkeiten, um komplexe soziale und politische Themen zu diskutieren und zu debattieren',
      zh: '培养讨论和辩论复杂社会和政治话题的技能',
      ru: 'Развивайте навыки обсуждения и дебатов по сложным социальным и политическим темам',
    },
    objectives: [
      'Present arguments logically',
      'Counter opposing viewpoints',
      'Use advanced connectors',
      'Maintain register in formal debates',
    ],
    estimatedMinutes: 35,
    order: 2,
    vocabulary: [
      {
        spanish: 'Por un lado... por otro lado',
        pronunciation: 'pohr oon LAH-doh... pohr OH-troh LAH-doh',
        translations: { en: 'On one hand... on the other hand', es: 'Por un lado... por otro lado', ar: 'من ناحية... من ناحية أخرى', fr: 'D\'un côté... de l\'autre côté', it: 'Da un lato... dall\'altro lato', de: 'Einerseits... andererseits', zh: '一方面...另一方面', ru: 'С одной стороны... с другой стороны' },
        partOfSpeech: 'phrase',
        exampleSentence: 'Por un lado es caro, pero por otro lado es de alta calidad.',
        exampleTranslation: 'On one hand it\'s expensive, but on the other hand it\'s high quality.',
      },
      {
        spanish: 'Sin embargo',
        pronunciation: 'seen ehm-BAHR-goh',
        translations: { en: 'However', es: 'Sin embargo', ar: 'ومع ذلك', fr: 'Cependant', it: 'Tuttavia', de: 'Jedoch', zh: '然而', ru: 'Однако' },
        partOfSpeech: 'conjunction',
        exampleSentence: 'Es difícil. Sin embargo, no es imposible.',
        exampleTranslation: 'It\'s difficult. However, it\'s not impossible.',
      },
    ],
    grammarPoints: [
      'Advanced connectors and discourse markers',
      'Passive voice for objectivity',
      'Impersonal constructions',
      'Hedging language',
    ],
    exercises: [
      {
        id: 'b2-02-ex1',
        type: 'translation',
        question: 'Translate: "Although I understand your point, I must disagree."',
        correctAnswer: 'Aunque entiendo tu punto, debo discrepar.',
        explanation: '"Aunque" (although) is followed by indicative when stating a fact.',
        points: 20,
      },
    ],
  },

  // ==================== C1 LESSONS ====================
  {
    id: 'c1-01',
    slug: 'professional-spanish',
    cefrLevel: 'C1',
    category: 'professional',
    title: {
      en: 'Professional and Business Spanish',
      es: 'Español Profesional y de Negocios',
      ar: 'الإسبانية المهنية والتجارية',
      fr: 'Espagnol Professionnel et des Affaires',
      it: 'Spagnolo Professionale e Commerciale',
      de: 'Professionelles und Geschäftsspanisch',
      zh: '专业和商务西班牙语',
      ru: 'Профессиональный и Деловой Испанский',
    },
    description: {
      en: 'Master Spanish for professional and business contexts',
      es: 'Domina el español para contextos profesionales y de negocios',
      ar: 'أتقن الإسبانية للسياقات المهنية والتجارية',
      fr: 'Maîtrisez l\'espagnol pour les contextes professionnels et commerciaux',
      it: 'Padroneggia lo spagnolo per contesti professionali e commerciali',
      de: 'Beherrschen Sie Spanisch für professionelle und geschäftliche Kontexte',
      zh: '掌握专业和商务场合的西班牙语',
      ru: 'Освойте испанский для профессиональных и деловых контекстов',
    },
    objectives: [
      'Write formal business emails',
      'Conduct meetings in Spanish',
      'Negotiate and present proposals',
      'Use appropriate register in professional settings',
    ],
    estimatedMinutes: 40,
    order: 1,
    vocabulary: [
      {
        spanish: 'Estimado/a',
        pronunciation: 'ehs-tee-MAH-doh/dah',
        translations: { en: 'Dear (formal)', es: 'Estimado/a', ar: 'عزيزي/عزيزتي', fr: 'Cher/Chère', it: 'Egregio/a', de: 'Sehr geehrte/r', zh: '尊敬的', ru: 'Уважаемый/ая' },
        partOfSpeech: 'adjective',
        exampleSentence: 'Estimada Sra. López, le escribo para...',
        exampleTranslation: 'Dear Mrs. López, I am writing to...',
      },
      {
        spanish: 'Atentamente',
        pronunciation: 'ah-tehn-tah-MEHN-teh',
        translations: { en: 'Sincerely', es: 'Atentamente', ar: 'مع خالص التحية', fr: 'Cordialement', it: 'Cordiali saluti', de: 'Mit freundlichen Grüßen', zh: '此致敬礼', ru: 'С уважением' },
        partOfSpeech: 'adverb',
        exampleSentence: 'Quedo a su disposición. Atentamente, Juan Pérez.',
        exampleTranslation: 'I remain at your disposal. Sincerely, Juan Pérez.',
      },
      {
        spanish: 'Adjuntar',
        pronunciation: 'ahd-hoon-TAHR',
        translations: { en: 'To attach', es: 'Adjuntar', ar: 'إرفاق', fr: 'Joindre', it: 'Allegare', de: 'Anhängen', zh: '附上', ru: 'Прикрепить' },
        partOfSpeech: 'verb',
        exampleSentence: 'Adjunto mi currículum para su consideración.',
        exampleTranslation: 'I attach my CV for your consideration.',
      },
    ],
    grammarPoints: [
      'Formal register and usted forms',
      'Business letter structure',
      'Subjunctive in formal requests',
      'Passive and impersonal constructions',
    ],
    exercises: [
      {
        id: 'c1-01-ex1',
        type: 'translation',
        question: 'Translate: "I would be grateful if you could send me the report."',
        correctAnswer: 'Le agradecería que me enviara el informe.',
        explanation: 'Formal requests use conditional + subjunctive structure.',
        points: 20,
      },
    ],
  },
  {
    id: 'c1-02',
    slug: 'regional-variations',
    cefrLevel: 'C1',
    category: 'culture',
    title: {
      en: 'Regional Variations: Spain vs Latin America',
      es: 'Variaciones Regionales: España vs Latinoamérica',
      ar: 'الاختلافات الإقليمية: إسبانيا مقابل أمريكا اللاتينية',
      fr: 'Variations Régionales : Espagne vs Amérique Latine',
      it: 'Variazioni Regionali: Spagna vs America Latina',
      de: 'Regionale Variationen: Spanien vs Lateinamerika',
      zh: '地区差异：西班牙与拉丁美洲',
      ru: 'Региональные Различия: Испания vs Латинская Америка',
    },
    description: {
      en: 'Understand and navigate the differences between Spanish varieties',
      es: 'Comprende y navega las diferencias entre las variedades del español',
      ar: 'افهم وتنقل بين الاختلافات بين أنواع الإسبانية',
      fr: 'Comprenez et naviguez entre les différences des variétés espagnoles',
      it: 'Comprendi e naviga le differenze tra le varietà spagnole',
      de: 'Verstehen und navigieren Sie die Unterschiede zwischen spanischen Varietäten',
      zh: '理解和掌握西班牙语变体之间的差异',
      ru: 'Понимайте и ориентируйтесь в различиях между вариантами испанского',
    },
    objectives: [
      'Recognize voseo and its conjugations',
      'Understand vocabulary differences',
      'Identify pronunciation variations',
      'Adapt to different Spanish-speaking contexts',
    ],
    estimatedMinutes: 35,
    order: 2,
    vocabulary: [
      {
        spanish: 'vos (Argentina)',
        pronunciation: 'bohs',
        translations: { en: 'you (informal, Argentina)', es: 'vos', ar: 'أنت (غير رسمي، الأرجنتين)', fr: 'tu (Argentine)', it: 'tu (Argentina)', de: 'du (Argentinien)', zh: '你（阿根廷非正式）', ru: 'ты (Аргентина)' },
        partOfSpeech: 'pronoun',
        exampleSentence: '¿Vos querés venir? (Argentina)',
        exampleTranslation: 'Do you want to come?',
      },
      {
        spanish: 'coche/carro/auto',
        pronunciation: 'KOH-cheh/KAH-rroh/OW-toh',
        translations: { en: 'car (Spain/Mexico/Argentina)', es: 'coche/carro/auto', ar: 'سيارة', fr: 'voiture', it: 'macchina', de: 'Auto', zh: '汽车', ru: 'машина' },
        partOfSpeech: 'noun',
        exampleSentence: 'Voy en coche. (Spain) / Voy en carro. (Mexico)',
        exampleTranslation: 'I\'m going by car.',
      },
    ],
    grammarPoints: [
      'Voseo conjugation patterns',
      'Leísmo, laísmo, loísmo',
      'Use of vosotros vs ustedes',
      'Regional vocabulary lists',
    ],
    exercises: [
      {
        id: 'c1-02-ex1',
        type: 'multiple_choice',
        question: 'In Argentina, how would you say "You speak" (informal)?',
        options: ['Tú hablas', 'Vos hablás', 'Usted habla', 'Vosotros habláis'],
        correctAnswer: 'Vos hablás',
        explanation: 'Argentina uses voseo: vos + verb with stress on final syllable (hablás).',
        points: 15,
      },
    ],
  },

  // ==================== C2 LESSONS ====================
  {
    id: 'c2-01',
    slug: 'literary-analysis',
    cefrLevel: 'C2',
    category: 'literature',
    title: {
      en: 'Literary Analysis and Critique',
      es: 'Análisis y Crítica Literaria',
      ar: 'التحليل والنقد الأدبي',
      fr: 'Analyse et Critique Littéraire',
      it: 'Analisi e Critica Letteraria',
      de: 'Literarische Analyse und Kritik',
      zh: '文学分析与评论',
      ru: 'Литературный Анализ и Критика',
    },
    description: {
      en: 'Analyze and critique Spanish literature at a native level',
      es: 'Analiza y critica la literatura española a nivel nativo',
      ar: 'حلل وانتقد الأدب الإسباني على مستوى المتحدث الأصلي',
      fr: 'Analysez et critiquez la littérature espagnole à un niveau natif',
      it: 'Analizza e critica la letteratura spagnola a livello madrelingua',
      de: 'Analysieren und kritisieren Sie spanische Literatur auf Muttersprachlerniveau',
      zh: '以母语水平分析和评论西班牙文学',
      ru: 'Анализируйте и критикуйте испанскую литературу на уровне носителя',
    },
    objectives: [
      'Analyze literary devices and techniques',
      'Discuss themes and symbolism',
      'Compare literary movements',
      'Write critical essays in Spanish',
    ],
    estimatedMinutes: 50,
    order: 1,
    vocabulary: [
      {
        spanish: 'metáfora',
        pronunciation: 'meh-TAH-foh-rah',
        translations: { en: 'metaphor', es: 'metáfora', ar: 'استعارة', fr: 'métaphore', it: 'metafora', de: 'Metapher', zh: '隐喻', ru: 'метафора' },
        partOfSpeech: 'noun',
        exampleSentence: 'La vida es sueño es una metáfora central en Calderón.',
        exampleTranslation: 'Life is a dream is a central metaphor in Calderón.',
      },
      {
        spanish: 'el realismo mágico',
        pronunciation: 'ehl reh-ah-LEES-moh MAH-hee-koh',
        translations: { en: 'magical realism', es: 'el realismo mágico', ar: 'الواقعية السحرية', fr: 'le réalisme magique', it: 'il realismo magico', de: 'der magische Realismus', zh: '魔幻现实主义', ru: 'магический реализм' },
        partOfSpeech: 'noun',
        exampleSentence: 'García Márquez es el maestro del realismo mágico.',
        exampleTranslation: 'García Márquez is the master of magical realism.',
      },
      {
        spanish: 'la narrativa',
        pronunciation: 'lah nah-rrah-TEE-bah',
        translations: { en: 'narrative/fiction', es: 'la narrativa', ar: 'السرد', fr: 'le récit', it: 'la narrativa', de: 'die Erzählung', zh: '叙事', ru: 'повествование' },
        partOfSpeech: 'noun',
        exampleSentence: 'La narrativa del Boom latinoamericano revolucionó la literatura.',
        exampleTranslation: 'The narrative of the Latin American Boom revolutionized literature.',
      },
    ],
    grammarPoints: [
      'Literary register and style',
      'Complex sentence structures',
      'Subjunctive in literary contexts',
      'Historical present tense',
    ],
    culturalNotes: 'Spanish literature spans from medieval works like El Cantar de Mio Cid to the Latin American Boom of the 20th century, including Nobel laureates like García Márquez, Neruda, and Vargas Llosa.',
    exercises: [
      {
        id: 'c2-01-ex1',
        type: 'translation',
        question: 'Translate: "The author employs irony to critique the bourgeois society of his time."',
        correctAnswer: 'El autor emplea la ironía para criticar la sociedad burguesa de su época.',
        explanation: 'Literary analysis requires precise vocabulary and formal register.',
        points: 25,
      },
    ],
  },
  {
    id: 'c2-02',
    slug: 'philosophical-discourse',
    cefrLevel: 'C2',
    category: 'philosophy',
    title: {
      en: 'Philosophical Discourse in Spanish',
      es: 'Discurso Filosófico en Español',
      ar: 'الخطاب الفلسفي بالإسبانية',
      fr: 'Discours Philosophique en Espagnol',
      it: 'Discorso Filosofico in Spagnolo',
      de: 'Philosophischer Diskurs auf Spanisch',
      zh: '西班牙语哲学论述',
      ru: 'Философский Дискурс на Испанском',
    },
    description: {
      en: 'Engage with complex philosophical concepts and arguments in Spanish',
      es: 'Participa en conceptos y argumentos filosóficos complejos en español',
      ar: 'شارك في المفاهيم والحجج الفلسفية المعقدة بالإسبانية',
      fr: 'Engagez-vous avec des concepts et arguments philosophiques complexes en espagnol',
      it: 'Confrontati con concetti e argomenti filosofici complessi in spagnolo',
      de: 'Setzen Sie sich mit komplexen philosophischen Konzepten und Argumenten auf Spanisch auseinander',
      zh: '用西班牙语参与复杂的哲学概念和论证',
      ru: 'Работайте со сложными философскими концепциями и аргументами на испанском',
    },
    objectives: [
      'Discuss existentialist philosophy',
      'Analyze ethical arguments',
      'Present complex abstract ideas',
      'Engage in Socratic dialogue',
    ],
    estimatedMinutes: 45,
    order: 2,
    vocabulary: [
      {
        spanish: 'el ser',
        pronunciation: 'ehl sehr',
        translations: { en: 'being/existence', es: 'el ser', ar: 'الوجود', fr: 'l\'être', it: 'l\'essere', de: 'das Sein', zh: '存在', ru: 'бытие' },
        partOfSpeech: 'noun',
        exampleSentence: 'Heidegger reflexiona sobre el ser y el tiempo.',
        exampleTranslation: 'Heidegger reflects on being and time.',
      },
      {
        spanish: 'la ética',
        pronunciation: 'lah EH-tee-kah',
        translations: { en: 'ethics', es: 'la ética', ar: 'الأخلاق', fr: 'l\'éthique', it: 'l\'etica', de: 'die Ethik', zh: '伦理学', ru: 'этика' },
        partOfSpeech: 'noun',
        exampleSentence: 'La ética de Spinoza influenció el pensamiento moderno.',
        exampleTranslation: 'Spinoza\'s ethics influenced modern thought.',
      },
      {
        spanish: 'el libre albedrío',
        pronunciation: 'ehl LEE-breh ahl-beh-DREE-oh',
        translations: { en: 'free will', es: 'el libre albedrío', ar: 'الإرادة الحرة', fr: 'le libre arbitre', it: 'il libero arbitrio', de: 'der freie Wille', zh: '自由意志', ru: 'свобода воли' },
        partOfSpeech: 'noun',
        exampleSentence: '¿Existe realmente el libre albedrío?',
        exampleTranslation: 'Does free will really exist?',
      },
    ],
    grammarPoints: [
      'Abstract noun usage',
      'Complex subordinate clauses',
      'Hypothetical and counterfactual constructions',
      'Academic writing conventions',
    ],
    exercises: [
      {
        id: 'c2-02-ex1',
        type: 'translation',
        question: 'Translate: "The paradox of freedom lies in the fact that true liberty requires self-imposed constraints."',
        correctAnswer: 'La paradoja de la libertad radica en el hecho de que la verdadera libertad requiere restricciones autoimpuestas.',
        explanation: 'Philosophical discourse requires precise abstract vocabulary and complex syntax.',
        points: 25,
      },
    ],
  },
  {
    id: 'c2-03',
    slug: 'cultural-subtleties-humor',
    cefrLevel: 'C2',
    category: 'culture',
    title: {
      en: 'Cultural Subtleties and Spanish Humor',
      es: 'Sutilezas Culturales y Humor Español',
      ar: 'الدقائق الثقافية والفكاهة الإسبانية',
      fr: 'Subtilités Culturelles et Humour Espagnol',
      it: 'Sottigliezze Culturali e Umorismo Spagnolo',
      de: 'Kulturelle Feinheiten und Spanischer Humor',
      zh: '文化微妙之处和西班牙幽默',
      ru: 'Культурные Тонкости и Испанский Юмор',
    },
    description: {
      en: 'Master the nuances of Spanish humor, idioms, and cultural references',
      es: 'Domina los matices del humor español, modismos y referencias culturales',
      ar: 'أتقن الفروق الدقيقة في الفكاهة الإسبانية والتعابير والمراجع الثقافية',
      fr: 'Maîtrisez les nuances de l\'humour espagnol, des expressions idiomatiques et des références culturelles',
      it: 'Padroneggia le sfumature dell\'umorismo spagnolo, dei modi di dire e dei riferimenti culturali',
      de: 'Beherrschen Sie die Nuancen des spanischen Humors, der Redewendungen und kulturellen Referenzen',
      zh: '掌握西班牙幽默、习语和文化参考的细微差别',
      ru: 'Освойте нюансы испанского юмора, идиом и культурных отсылок',
    },
    objectives: [
      'Understand and use Spanish wordplay',
      'Recognize cultural references in humor',
      'Use irony and sarcasm appropriately',
      'Navigate regional humor differences',
    ],
    estimatedMinutes: 40,
    order: 3,
    vocabulary: [
      {
        spanish: 'doble sentido',
        pronunciation: 'DOH-bleh sehn-TEE-doh',
        translations: { en: 'double meaning/pun', es: 'doble sentido', ar: 'معنى مزدوج', fr: 'double sens', it: 'doppio senso', de: 'Doppeldeutigkeit', zh: '双关语', ru: 'двойной смысл' },
        partOfSpeech: 'noun',
        exampleSentence: 'El chiste tiene un doble sentido muy gracioso.',
        exampleTranslation: 'The joke has a very funny double meaning.',
      },
      {
        spanish: 'cachondeo',
        pronunciation: 'kah-chohn-DEH-oh',
        translations: { en: 'joking around/banter', es: 'cachondeo', ar: 'مزاح', fr: 'plaisanterie', it: 'scherzare', de: 'Scherzen', zh: '开玩笑', ru: 'шутки' },
        partOfSpeech: 'noun',
        exampleSentence: 'Esto es un cachondeo, ¿no?',
        exampleTranslation: 'This is a joke, right?',
      },
      {
        spanish: 'quedarse con alguien',
        pronunciation: 'keh-DAHR-seh kohn AHL-gee-ehn',
        translations: { en: 'to pull someone\'s leg', es: 'quedarse con alguien', ar: 'يمزح مع شخص', fr: 'se moquer de quelqu\'un', it: 'prendere in giro qualcuno', de: 'jemanden auf den Arm nehmen', zh: '开某人玩笑', ru: 'разыгрывать кого-то' },
        partOfSpeech: 'phrase',
        exampleSentence: '¿Te estás quedando conmigo?',
        exampleTranslation: 'Are you pulling my leg?',
      },
    ],
    grammarPoints: [
      'Colloquial expressions and slang',
      'Diminutives for humor and affection',
      'Ironic use of language',
      'Regional expressions',
    ],
    culturalNotes: 'Spanish humor often relies on wordplay, irony, and cultural references. Understanding humor is considered a sign of true language mastery.',
    exercises: [
      {
        id: 'c2-03-ex1',
        type: 'multiple_choice',
        question: 'What does "No hay tu tía" mean?',
        options: ['Your aunt isn\'t here', 'There\'s no way/It\'s impossible', 'I don\'t have an aunt', 'Where is your aunt?'],
        correctAnswer: 'There\'s no way/It\'s impossible',
        explanation: 'This is an idiomatic expression meaning something is impossible. It comes from "atutía" (zinc oxide), a supposed cure-all.',
        points: 20,
      },
    ],
  },
  {
    id: 'c2-04',
    slug: 'legal-technical-spanish',
    cefrLevel: 'C2',
    category: 'professional',
    title: {
      en: 'Legal and Technical Spanish',
      es: 'Español Legal y Técnico',
      ar: 'الإسبانية القانونية والتقنية',
      fr: 'Espagnol Juridique et Technique',
      it: 'Spagnolo Legale e Tecnico',
      de: 'Juristisches und Technisches Spanisch',
      zh: '法律和技术西班牙语',
      ru: 'Юридический и Технический Испанский',
    },
    description: {
      en: 'Master specialized Spanish for legal and technical domains',
      es: 'Domina el español especializado para dominios legales y técnicos',
      ar: 'أتقن الإسبانية المتخصصة للمجالات القانونية والتقنية',
      fr: 'Maîtrisez l\'espagnol spécialisé pour les domaines juridiques et techniques',
      it: 'Padroneggia lo spagnolo specializzato per ambiti legali e tecnici',
      de: 'Beherrschen Sie spezialisiertes Spanisch für juristische und technische Bereiche',
      zh: '掌握法律和技术领域的专业西班牙语',
      ru: 'Освойте специализированный испанский для юридических и технических областей',
    },
    objectives: [
      'Read and understand legal documents',
      'Write technical reports',
      'Translate specialized texts',
      'Use domain-specific terminology',
    ],
    estimatedMinutes: 50,
    order: 4,
    vocabulary: [
      {
        spanish: 'el demandante',
        pronunciation: 'ehl deh-mahn-DAHN-teh',
        translations: { en: 'plaintiff', es: 'el demandante', ar: 'المدعي', fr: 'le demandeur', it: 'l\'attore', de: 'der Kläger', zh: '原告', ru: 'истец' },
        partOfSpeech: 'noun',
        exampleSentence: 'El demandante presentó pruebas contundentes.',
        exampleTranslation: 'The plaintiff presented compelling evidence.',
      },
      {
        spanish: 'el fallo',
        pronunciation: 'ehl FAH-yoh',
        translations: { en: 'verdict/ruling', es: 'el fallo', ar: 'الحكم', fr: 'le verdict', it: 'la sentenza', de: 'das Urteil', zh: '裁决', ru: 'приговор' },
        partOfSpeech: 'noun',
        exampleSentence: 'El tribunal emitió su fallo a favor del acusado.',
        exampleTranslation: 'The court issued its ruling in favor of the defendant.',
      },
      {
        spanish: 'la cláusula',
        pronunciation: 'lah KLOW-soo-lah',
        translations: { en: 'clause', es: 'la cláusula', ar: 'البند', fr: 'la clause', it: 'la clausola', de: 'die Klausel', zh: '条款', ru: 'пункт' },
        partOfSpeech: 'noun',
        exampleSentence: 'La cláusula de confidencialidad es vinculante.',
        exampleTranslation: 'The confidentiality clause is binding.',
      },
    ],
    grammarPoints: [
      'Legal terminology and formulas',
      'Passive constructions in legal texts',
      'Future subjunctive (archaic legal usage)',
      'Nominal style in technical writing',
    ],
    exercises: [
      {
        id: 'c2-04-ex1',
        type: 'translation',
        question: 'Translate: "The parties agree to submit any dispute to arbitration."',
        correctAnswer: 'Las partes acuerdan someter cualquier disputa a arbitraje.',
        explanation: 'Legal Spanish uses specific terminology and formal constructions.',
        points: 25,
      },
    ],
  },
  {
    id: 'c2-05',
    slug: 'simultaneous-interpretation',
    cefrLevel: 'C2',
    category: 'professional',
    title: {
      en: 'Simultaneous Interpretation Skills',
      es: 'Habilidades de Interpretación Simultánea',
      ar: 'مهارات الترجمة الفورية',
      fr: 'Compétences d\'Interprétation Simultanée',
      it: 'Competenze di Interpretazione Simultanea',
      de: 'Simultandolmetsch-Fähigkeiten',
      zh: '同声传译技能',
      ru: 'Навыки Синхронного Перевода',
    },
    description: {
      en: 'Develop skills for real-time Spanish-English interpretation',
      es: 'Desarrolla habilidades para la interpretación español-inglés en tiempo real',
      ar: 'طور مهارات الترجمة الفورية بين الإسبانية والإنجليزية',
      fr: 'Développez des compétences pour l\'interprétation espagnol-anglais en temps réel',
      it: 'Sviluppa competenze per l\'interpretazione spagnolo-inglese in tempo reale',
      de: 'Entwickeln Sie Fähigkeiten für die Echtzeit-Spanisch-Englisch-Verdolmetschung',
      zh: '培养西班牙语-英语实时口译技能',
      ru: 'Развивайте навыки синхронного испанско-английского перевода',
    },
    objectives: [
      'Practice split attention techniques',
      'Develop rapid reformulation skills',
      'Handle specialized vocabulary on the fly',
      'Maintain accuracy under pressure',
    ],
    estimatedMinutes: 60,
    order: 5,
    vocabulary: [
      {
        spanish: 'la cabina de interpretación',
        pronunciation: 'lah kah-BEE-nah deh een-tehr-preh-tah-see-OHN',
        translations: { en: 'interpretation booth', es: 'la cabina de interpretación', ar: 'كابينة الترجمة', fr: 'la cabine d\'interprétation', it: 'la cabina di interpretazione', de: 'die Dolmetscherkabine', zh: '口译间', ru: 'кабина переводчика' },
        partOfSpeech: 'noun',
        exampleSentence: 'El intérprete trabaja desde la cabina de interpretación.',
        exampleTranslation: 'The interpreter works from the interpretation booth.',
      },
      {
        spanish: 'el décalage',
        pronunciation: 'ehl deh-kah-LAH-heh',
        translations: { en: 'lag/delay (in interpretation)', es: 'el décalage', ar: 'التأخر', fr: 'le décalage', it: 'il décalage', de: 'der Zeitversatz', zh: '时滞', ru: 'задержка' },
        partOfSpeech: 'noun',
        exampleSentence: 'Un buen intérprete mantiene un décalage mínimo.',
        exampleTranslation: 'A good interpreter maintains minimal lag.',
      },
    ],
    grammarPoints: [
      'Rapid syntactic restructuring',
      'Anticipation techniques',
      'Compression and expansion strategies',
      'Register adaptation in real-time',
    ],
    exercises: [
      {
        id: 'c2-05-ex1',
        type: 'speaking',
        question: 'Listen to the audio and provide a simultaneous interpretation into English.',
        correctAnswer: 'Evaluated by instructor',
        explanation: 'Simultaneous interpretation requires practice with real audio materials.',
        points: 30,
      },
    ],
  },
];

// Helper function to get lessons by level
export const getLessonsByLevel = (level: CEFRLevel): CurriculumLesson[] => {
  return CURRICULUM_LESSONS.filter(lesson => lesson.cefrLevel === level);
};

// Helper function to get level info
export const getLevelInfo = (code: CEFRLevel): CEFRLevelInfo | undefined => {
  return CEFR_LEVELS.find(level => level.code === code);
};

// Get total lessons count per level
export const getLessonCountByLevel = (): Record<CEFRLevel, number> => {
  const counts: Record<CEFRLevel, number> = { A1: 0, A2: 0, B1: 0, B2: 0, C1: 0, C2: 0 };
  CURRICULUM_LESSONS.forEach(lesson => {
    counts[lesson.cefrLevel]++;
  });
  return counts;
};
